name: Obla4ko
favicon: null
layout_spectrum: 0
typography_spectrum: 0.5250896
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#303030'
    - '#626262'
    - '#B7B7B7'
    - '#FCFCFC'
  brandStrength: 0.8351254
  lightness: 0.8440861
  saturation: 0.7383512
  rhythmicContrast: 0.6129032
purpose: []
